services:
  sekaid:
    build:
      context: ./
      dockerfile: sekai.Dockerfile
    volumes:
      - ./sekai:/sekai
    ports:
      - "26657:26657" # RPC
      - "26656:26656" # P2P (gRPC)
      - "26660:26660" # Prometheus
    entrypoint: ["/entrypoint.sh"]
    networks:
      - kiranet
    hostname: sekai.local

  interxd:
    build:
      context: ./
      dockerfile: interx.Dockerfile
    volumes:
      - ./interx:/interx
    ports:
      - "11000:11000"
    entrypoint: ["/entrypoint.sh"]
    networks:
      - kiranet
    hostname: interx.local

networks:
  kiranet:
    name: kiranet
    driver: bridge

